- src/core/class/column.lisp
- src/core/dao/mixin.lisp
- t/class.lisp
The new column type is DATETIME for MySQL & SQLite3, TIME for PostgreSQL.
> Change the column type of created_at/updated_at.

- .travis.yml
- mito-test.asd
- src/core/db.lisp
- t/postgres-types.lisp
* added convert-nulls-to-nils and list-convert-nulls-to-nils and use
them in retrieve-by-sql to convert :nulls to nils in lists and arrays
> retrieve-by-sql: recursively convert nulls to nils

- src/core/dao.lisp
This fixes an issue when using `where-and` with dashed field names. Dashes were not correctly being converted to use underscores which caused `count-dao` to return incorrect results.
For example:
```lisp
(mito:count-dao 'mytable :some-dashed-field "value")
```
Would always return 0, because the generated SQL would not convert dashes to underscores:
```lisp
#<SXQL-CLAUSE: WHERE (some-dashed-field = 'value')>
```
This change adds the missing field name conversion.
> Fix issue when using `where-and` with dashed field names

- t/postgres-types.lisp
* fix expected values for text (the default format) row values and add
new tests for binary row values.
Note that this requires Postmodern version 160ba03c0bf91563dcdce055e185e2f5b3301348 or later for the recent text/binary row value changes and for the null value Postmodern bug fixes.
> postgres row value tests

- src/core/db.lisp
This error was appeared when you are trying to generate-migrations for SQL database where some table
already exists.
This commit fixes issue #27.
> An error "DB Error: database table is locked (Code: LOCKED)" was fixed.

- src/core/dao.lisp
Fix so that mito:includes works in the following cases, in which col-type of tel is optional.
```common-lisp
(defclass user ()
((name :col-type (:varchar 64)
:initarg :name
:accessor user-name)
(email :col-type (or (:varchar 128) :null)
:initarg :email
:accessor user-email)
(tel :col-type (or optional-info :null)))
(:metaclass mito:dao-table-class))
(defclass optional-info ()
((tel :col-type :text
:initarg :tel
:accessor optional-info-tel))
(:metaclass mito:dao-table-class))
(mito:select-dao 'user (mito:includes 'optional-info))
```
> Fix include-foreign-objects to allow contain nil

- src/core/dao/table.lisp
`make-dao-instance`, which is called when retrieving rows from DB, initializes slots, including relational ones.
It causes an unexpected behaviour that relational slots with `:initform` will always be initialized with the default value.
For example,
```
(defclass user ()
((name :col-type (:varchar 128)
:initarg :name))
(:metaclass dao-table-class))
(defclass wallet ()
((user :col-type user
:initarg :user
:initform (mito:find-dao 'user :id 1)))
(:metaclass dao-table-class))
(defvar *user* (mito:find-dao 'user :id 99))
(mito:create-dao 'wallet :user *user*)
;; 'user' of this 'wallet' would be user<id=1>, though it's <id=99> in DB.
(mito:find-dao 'wallet :user *user*)
```
This patch replace `make-instance` by `allocate-instance` & `shared-initialize` for preventing from slot initialization.
> Skip initialization in make-dao-instance

- README.markdown
- src/core.lisp
- src/core/class/column.lisp
- src/core/dao.lisp
- src/core/dao/column.lisp
- src/core/dao/table.lisp
This is a common pattern of defining a table class:
```common-lisp
(defclass user ()
((name :col-type (:varchar 64)
:initarg :name
:accessor user-name)
(email :col-type (or (:varchar 128) :null)
:initarg :email
:accessor user-email))
(:metaclass mito:dao-table-class))
```
With this patch, it can be written like this:
```common-lisp
(mito:deftable user ()
((name :col-type (:varchar 64))
(email :col-type (or (:varchar 128) :null))))
```
`deftable` adds the default `:initarg` and `:accessor`, so those are still available.
```common-lisp
(user-name (make-instance 'user :name "fukamachi'))
;=> "fukamachi"
```
The default accessor prefix can be changed with `:conc-name` class option.
```common-lisp
(mito:deftable user ()
((name :col-type (:varchar 64))
(email :col-type (or (:varchar 128) …
```
> Default initargs and accessors

- src/core/connection.lisp
This is a minor PR but it could simplify the api.
By default `*connection*` is unbound when we are not connected to a DB.
Now we can always check it without being cautious with a
`(and (boundp ...) ...)` or better `mito:connected-p`.
I don't see the benefits of keeping this variable unbound, when all connected-p does is checking it isn't null, and given the variable is exported and encouraged for use.
Thanks.
> initialize *connection* to nil

- README.markdown
- src/core.lisp
- src/core/connection.lisp
This is just a wrapper around a dbi method, but it is very handy for me and I have wanted this for a long time.  I didn't find easily (enough) about the dbi method, I had to follow layers of sources. Having this is easier for auto-discovery and more handy than inspect.
Regards
> add connection-database-name function

- src/core.lisp
- src/core/logger.lisp
I want to silence migrations during my unit tests, so I don't want
this macro to always write to standard-output.
I figured that `*mito-logger-stream*` is used elsewhere and is better staying at nil, hence the new variable.
Regards
> new variable to control the output stream of with-sql-logging

- src/core/dao.lisp
I want to use the sxql struct which is used for querying in select-dao for other purposes(e.g. for paging),
so changed select-dao to return multiple values.
> Change select-dao to return also sxql struct as values

- roswell/mito.ros
This is useful when your dev database is on a remote server or in a separate docker container.
> Added the --host and --port arguments to connect to remote databases.

- src/core/db.lisp
- src/core/db/mysql.lisp
- src/core/db/postgres.lisp
- src/core/db/sqlite3.lisp
- src/core/util.lisp
Introduce a macro WITH-PREPARED-QUERY. Given a connection and sql statement, it
prepares a statement, binds it to desired name, executes the body, and then
cleans up the query with an UNWIND-PROTECT.
Replaced all calls to DBI:PREPARE with the equivalent WITH-PREPARED-BODY.
This helps prevent unused resources from piling up. As an example, cl-sqlite
finalizes all queries when the database connection is closed. In a program that
connects, performs millions of queries, and then disconnects, the disconnect
will take a ridiculous amount of time to perform if the resources are not freed
immediately after use.
> Free query resources after use

- src/core/dao.lisp
This makes possible to write SQL by hand in cases where you need
something complex like that:
(mito.dao:select-by-sql
'top-item
"SELECT * FROM (
SELECT score.*,
row_number() OVER (ORDER BY total DESC) AS position
FROM score
) AS t
WHERE position > ?
ORDER BY position
LIMIT ?"
:binds (list (- user-position
(floor (/ limit 2)))
limit))
> Function select-by-sql was exported and now accepts :binds parameter like retrieve-by-sql

- src/core/db.lisp
- src/core/logger.lisp
CL-DBI provides a logging feature since v0.9.0. This patch replaces Mito.Logger by it.
Compatibility note: functions in `*trace-sql-hooks*` now takes these 5 arguments, not 3.
* SQL (string)
* params (list)
* Row counts (integer or null)
* Took time in milliseconds (integer or null)
* Previous stack call (symbol, cons or null)
> Use DBI logger for logging

- src/core/dao.lisp
I encounter this error from PostgreSQL:
2020-11-08 15:03:44.000 UTC [30315] ERROR:  currval of sequence "dist_id_seq" is not yet defined in this session
2020-11-08 15:03:44.000 UTC [30315] STATEMENT:  SELECT currval(pg_get_serial_sequence('dist', 'id')) AS last_insert_id
2020-11-08 15:03:44.001 UTC [30315] ERROR:  current transaction is aborted, commands ignored until end of transaction block
When trying to pass an object with `id` into the `insert-dao`.
This is a rare situation because I'm having a composite primary key on my object: `(id version)`
ID field is autoincremented, but version is not.
When I create a new object version, I call `insert-dao` on the object where ID slot has value and VERSION slot
is incremented by application code. This leads to the error, because Mito tries to …
> Fixed error when insert-dao used with object having the value for the serial-key

- src/migration/sql-parse.lisp
This change ensures that the symbol associated with the SPACE rule is
MITO.MIGRATION.SQL-PARSE::SPACE rather than COMMON-LISP:SPACE which
helps prevent conflicts with other ESRAP grammars in the same image.
> Keep from polluting COMMON-LISP with ESRAP rules

- docker/entrypoint.sh
- lack-middleware-mito.asd
- mito-core.asd
- src/core.lisp
- src/core/db.lisp
- src/core/logger.lisp
- src/core/util.lisp
- t/db/main.lisp
This feature is experimental. To enable this, set `*USE-PREPARE-CACHED*` T.
ref https://github.com/fukamachi/cl-dbi/pull/56
> Allow to use DBI:PREPARE-CACHED instead of DBI:PREPARE.

- src/core/dao.lisp
Before this, `(mito:create-dao :some-id "xxxx")` is not allowed and just ignored.
By this changes, it's allowed and still `(mito:create-dao :some #<obj>)` is okay.
> Use the references ID column in mito:save-dao when it's bound.

- src/core/logger.lisp
> Fix the logger to work even when the call function is an uninterned symbol

- src/core/dao/mixin.lisp
Before ad6d1fde779fd71e7fc95c2ce380c14154ac0e42 commit `MAKE-DAO-INSTANCE` function applied `ENSURE-CLASS` to the first argument. After this commit, this behaviour was broken and the function `SELECT-BY-SQL` was broken as well, because it does not apply `ENSURE-CLASS` as other `DAO` functions do.
> Make MAKE-DAO-INSTANCE accept symbolic class names.

- src/core/dao.lisp
Useful for macros. Also, currently, if you have more than one INCLUDES clause in SELECT-DAO all but the last one are silently ignored.
> Allow multiple INCLUDES

- src/core/connection.lisp
Function `disconnect-toplevel` calls `makunbound` on variable `*connection*`.
The following code fails unconditionally:
```lisp
(mito:disconnect-toplevel)
(mito.connection:connected-p) ; => Error: The variable *CONNECTION* is unbound.
```
This PR fixes this issue.
#106
> Fix unbound *connection* error after disconnected

- .github/workflows/ci.yml
- src/migration/versions.lisp
When creating the DB, the latest schema version was recorded until now.
New migration files created thereafter are applied sequentially.
However, it may confuse when another branch has "older" migration files, which won't be applied.
This patch fixes the problem by recording all existing schema versions on the first DB creation.
> Record all existing migration versions on the first table creation.

- src/core/db/postgres.lisp
- src/migration/versions.lisp
Also pg_advisory_lock call was updated for the latest cl-dbi. This closes issue #115
> Fix issue in initial migration.

- README.markdown
There doesn't seem to be a documented way to select with a raw SQL query, so I added a reference to `mito.dao:select-by-sql` in the README.
> Added reference to select-by-sql in documentation

- README.markdown
I've used mito for some of my personal projects and found it neat. But I often found myself going to libraries such as datafly because I didn't know how to do a complex query in mito. It turns out that mito actually implements the same facilities but they weren't documented anywhere. So I've documented them myself for future users.
Also, turns out a clack middleware exists. Had no idea about that until I accidentally came across it while read through some of the code.
> Document the clack middleware and `retrieve-by-sql`

- src/core/class/column.lisp
- src/core/dao/mixin.lisp
- src/core/logger.lisp
Some variables are removed and some are ignored.
Compiling `Mito` works now without style warnings on `sbcl` 2.4.3.
The test suites are not set up on my machine so you should run the tests
at least one time to make sure nothing is breaking with this change.
> Fix: avoid unused variable style warnings

- src/core/db.lisp
* `:format`:
* The format of each row in results. Must be one of `:plist`, `:alist`, `:hash-table` and `:values`.
* The default is `:plist`.
* `:lispify`:
* A flag whether keys in result rows are converted to upcased kebab keywords.
* If `:format` is `:plist` (default), this is `t`. Otherwise, it is `nil`.
> Add `:format` and `:lispify` to `retrieve-by-sql`

- src/core/dao.lisp
- t/dao.lisp
The affected functions are:
* `find-dao`
* `retrieve-dao`
* `count-dao`
* `delete-by-values`
> Generate `IS NULL` query by specifying `NIL` for key-value style query functions.
